name: CLEAR
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - argon2-cffi=20.1.0=py38h497a2fe_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.3.0=pyh44b312d_0
  - brotlipy=0.7.0=py38h497a2fe_1001
  - cachecontrol=0.12.6=py_0
  - cachy=0.3.0=py_0
  - cairo=1.16.0=h18b612c_1001
  - cffi=1.14.5=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - cleo=0.7.6=py_0
  - clikit=0.4.3=pyh9f0ad1d_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - commonmark=0.9.1=py_0
  - cryptography=3.4.4=py38h3e25421_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - et_xmlfile=1.0.1=py_1001
  - future=0.18.2=py38h578d9bd_3
  - gmp=6.2.1=h58526e2_0
  - html5lib=1.1=pyh9f0ad1d_0
  - hyperopt=0.1.2=py_0
  - idna=2.10=pyh9f0ad1d_0
  - igraph=0.7.1=h2166141_1005
  - importlib-metadata=3.7.0=py38h578d9bd_0
  - ipykernel=5.5.0=py38h81c977d_1
  - ipython=7.21.0=py38h81c977d_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jdcal=1.4.1=py_0
  - jedi=0.18.0=py38h578d9bd_2
  - jeepney=0.6.0=pyhd8ed1ab_0
  - jinja2=2.11.3=pyh44b312d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.1=py38h578d9bd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - keyring=18.0.1=py38h32f6830_0
  - leidenalg=0.8.3=py38he726ab7_0
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=7.5.0=h14aa051_18
  - libgfortran4=7.5.0=h14aa051_18
  - libgomp=9.3.0=h2828fa1_18
  - libiconv=1.16=h516909a_0
  - libsodium=1.0.18=h36c2ea0_1
  - lockfile=0.12.2=py_1
  - markupsafe=1.1.1=py38h497a2fe_3
  - mistune=0.8.4=py38h497a2fe_1003
  - msgpack-python=1.0.0=py38h82cb98a_2
  - natsort=7.1.1=pyhd8ed1ab_0
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py38h578d9bd_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - networkx=2.5=py_0
  - notebook=6.2.0=py38h578d9bd_0
  - openpyxl=3.0.6=pyhd8ed1ab_0
  - packaging=20.9=pyh44b312d_0
  - pandoc=2.11.4=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - pastel=0.2.0=py_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pixman=0.38.0=h516909a_1003
  - pkginfo=1.7.0=pyhd8ed1ab_0
  - poetry=1.0.10=py38h32f6830_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.16=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycairo=1.20.0=py38h323dad1_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.0=pyhd8ed1ab_0
  - pylev=1.3.0=py_0
  - pymongo=3.11.0=py38h348cfbe_4
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyrsistent=0.14.11=py38h497a2fe_2
  - pysocks=1.7.1=py38h578d9bd_3
  - python-igraph=0.7.1.post7=py38h516909a_0
  - python_abi=3.8=1_cp38
  - pyzmq=20.0.0=py38h1d1b12f_1
  - requests=2.25.1=pyhd3deb0d_0
  - requests-toolbelt=0.8.0=py_1
  - rich=9.12.4=py38h578d9bd_0
  - secretstorage=3.3.1=py38h578d9bd_0
  - send2trash=1.5.0=py_0
  - shellingham=1.4.0=pyh44b312d_0
  - terminado=0.9.2=py38h578d9bd_0
  - testpath=0.4.4=py_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomlkit=0.5.11=py38h32f6830_1
  - tqdm=4.58.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - urllib3=1.26.3=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - widgetsnbextension=3.5.1=py38h578d9bd_4
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.2=h470a237_5
  - xorg-libx11=1.7.0=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - zeromq=4.3.3=h58526e2_3
  - zipp=3.4.0=py_0
  - blas=1.0=mkl
  - blosc=1.21.0=h8c45485_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.5.25=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py38_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.66.1=h92f7085_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - intel-openmp=2020.2=254
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py38h2531618_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - llvmlite=0.34.0=py38h269e1b5_4
  - lz4-c=1.9.3=h2531618_0
  - lzo=2.10=h7b6447c_2
  - matplotlib=3.3.2=h06a4308_0
  - matplotlib-base=3.3.2=py38h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - mock=4.0.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py38hff7bd54_0
  - numba=0.51.2=py38h0573a6f_1
  - numexpr=2.7.3=py38hb2eb853_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=py_0
  - openssl=1.1.1k=h27cfd23_0
  - pandas=1.2.1=py38ha9443f7_0
  - patsy=0.5.1=py38_0
  - pcre=8.44=he6710b0_0
  - pillow=8.1.0=py38he98fc37_0
  - pip=20.3.3=py38h06a4308_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pytables=3.6.1=py38h9fd0a39_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - scikit-learn=0.24.1=py38ha9443f7_0
  - scipy=1.6.1=py38h91f5cce_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - setuptools=52.0.0=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=pyhd3eb1b0_0
  - sqlite=3.33.0=h62c20be_0
  - statsmodels=0.12.2=py38h27cfd23_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py38h27cfd23_0
  - typing-extensions=3.7.4.3=hd3eb1b0_0
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - faiss-gpu=1.7.0=py3.8_h080d439_0_cuda10.2
  - libfaiss=1.7.0=h4fe19ad_0_cuda10.2
  - pytorch=1.7.1=py3.8_cuda10.2.89_cudnn7.6.5_0
  - torchaudio=0.7.2=py38
  - torchvision=0.8.2=py38_cu102
  - pip:
    - absl-py==0.11.0
    - addict==2.4.0
    - aiohttp==3.7.4
    - anndata==0.7.5
    - async-timeout==3.0.1
    - biopython==1.78
    - cachetools==4.2.1
    - faiss==1.7.0
    - fsspec==0.8.7
    - get-version==2.1
    - google-auth==1.25.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.35.0
    - h5py==3.1.0
    - legacy-api-wrap==1.2
    - markdown==3.3.3
    - mmcv==1.2.6
    - msgpack==1.0.0
    - multidict==5.1.0
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - opt-einsum==3.3.0
    - protobuf==3.14.0
    - ptflops==0.6.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pynndescent==0.5.2
    - pyro-api==0.1.2
    - pyro-ppl==1.6.0
    - pytorch-ignite==0.4.2
    - pytorch-lightning==1.2.1
    - pyyaml==5.3.1
    - requests-oauthlib==1.3.0
    - rsa==4.7
    - scanpy==1.7.1
    - scikit-misc==0.1.3
    - scvi-tools==0.9.0
    - sinfo==0.3.1
    - stdlib-list==0.8.0
    - tables==3.6.1
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - torch==1.8.0
    - umap-learn==0.5.1
    - werkzeug==1.0.1
    - yacs==0.1.8
    - yapf==0.30.0
    - yarl==1.6.3
prefix: /home/yanhan/.conda/envs/DeepLearning

